twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    catgServ: '@App\Twig\CategoryServiceExtention'
    catgsArticle: '@App\Twig\CategoryArticleExtension'

when@test:
  twig:
    strict_variables: true
    form_themes: ["bootstrap_4_layout.html.twig"]
